fix: Add package update before installing neovimfix
- on fresh distro we could end up with error:

```
Package neovim is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Error: Package 'neovim' has no installation candidate
```